---
linters:
  disable-all: false
  enable-all: true
  disable:
    - gochecknoglobals
    - tagliatelle
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - paralleltest
    - ireturn
    - wrapcheck
    - forcetypeassert
    - maligned
    - depguard
    - tagalign
    - dupword
    - perfsprint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

linters-settings:
  cyclop:
    max-complexity: 16

  funlen:
    lines: 160
    statements: 50

  lll:
    line-length: 165

  dupl:
    threshold: 450

  gocognit:
    min-complexity: 50

  nestif:
    min-complexity: 20


run:
  concurrency: 10
  timeout: 10m
  issues-exit-code: 1
  tests: true

severity:
  default-severity: error

output:
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true
